VoyageAI vectorizer and reranker
redis/redis-vl-python pull request #152
Opened 2024-05-13 20:53 UTC by fzowl

2024-05-15 17:25 UTC, bsbodden reviewed
@tylerhutcherson LGTM!

2024-06-08 05:09 UTC, bsbodden commented
@fzowl there are tests failing in our test matrix, can you address them before the branch goes stale?

2024-06-08 10:17 UTC, fzowl commented
@bsbodden The failed tests seem to be related to GCP credentials, not during the code tests but during the Authenticate to GCP step, which is in your control, I believe. Can you please help me out with what the issue could be here?
<img width="1655" alt="Screenshot 2024-06-08 at 12 14 54" src="https://github.com/redis/redis-vl-python/assets/160063452/36173a6e-3b57-416f-8bfa-835fb5f56121">

2024-09-16 14:01 UTC, tylerhutcherson commented
Will take a look and see if we can get this wrapped up, thanks team!

2024-09-16 14:16 UTC, fzowl commented
@tylerhutcherson Thank you!

2024-09-19 12:40 UTC, fzowl commented
@tylerhutcherson Any progress on this? Is there anything i can help?

2024-09-20 13:31 UTC, tylerhutcherson commented on redisvl/utils/vectorize/text/voyageai.py
> +            input_type="search_query"
https://docs.voyageai.com/docs/embeddings -- input_types are different than cohere's

2024-09-20 13:33 UTC, tylerhutcherson commented on tests/integration/test_rerankers.py
> +def test_rank_documents_cohere(reranker):
I like the fixture updates here! can we make the test method names generic too

2024-09-20 13:34 UTC, tylerhutcherson requested changes
Overall it's great -- just a few things I caught when reviewing. I will get an API key today to set up in our CI. Also looks like there is an issue with the lockfile:

https://github.com/redis/redis-vl-python/actions/runs/10885688987/job/30434690376?pr=152

2024-09-21 14:23 UTC, tylerhutcherson commented
FYI @fzowl im working on fixing tests over here: https://github.com/redis/redis-vl-python/pull/223
will merge when I have it all working. Needed to address the lockfile, formatting/linting, and one other thing.

2024-09-21 14:26 UTC, fzowl commented
@tylerhutcherson Thank you very much! I was struggling a bit with the lockfile, i tried to update it but it was hanging every time for me. Thank you very much for your help!

2024-09-21 14:28 UTC, tylerhutcherson commented
> @tylerhutcherson Thank you very much! I was struggling a bit with the lockfile, i tried to update it but it was hanging every time for me. Thank you very much for your help!

No problem! We're happy to support more integrations, and sorry this took so long. We just had a slew of customer requests we needed to focus on first. @fzowl I will close this PR in favor of the other, and plan to release soon. Will VoyageAI do any kind of announcement about the new integration or maybe host an example in your docs? That would be rad.

2024-09-21 14:28 UTC, closed without merging

2024-09-21 14:43 UTC, fzowl commented
@tylerhutcherson Yes, i will add RedisVL to our integrations in our site.
I have one more question, is the API documentation automatically generated or shall i extend with VoyageAI? (https://www.redisvl.com/api/vectorizer.html)